### PR TITLE
[regression] Fix entrypoint to package

### PR DESCRIPTION
**Pull request by willsoto**
**This was working in 6.0.0-alpha.2**

The module's entrypoint does not reside in `dist`, it is in `lib`. I am not sure if the intention is to have it in `dist` but the only folder included when the module is installed is `lib`. I'm not even sure how it is ending up in `lib` because the [`tsconfig.json` points to `dist`](https://github.com/mentos1386/nest-raven/blob/master/tsconfig.json#L12).

At the moment, this module is not working since node is unable to resolve an entrypoint.

```
❯ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> require.resolve("nest-raven")
Uncaught Error: Cannot find module 'nest-raven'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
```

Here is an image of the on-disk structure of this package after installation. 

Screen Shot 2020-08-27 at 3 37 42 PM

### CODE REVIEW

**Comment by willsoto** [comment]
Nevermind. I am not sure what version of the package I was getting now. Could be the same issue as #105.
